name: identity_prototype

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.15.0

  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  crypto: ^3.0.3

  flutter_svg: ^2.0.7

  image_gallery_saver: ^2.0.3

  camera: ^0.10.5+9

  image_picker: ^1.1.2
  qr_code_tools: ^0.2.0
  zxing2: ^0.2.4

dev_dependencies:
  flutter_lints: ^6.0.0